name: CI

on:
  push:
    branches:
      - main

jobs:
  install-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Package Installation
        run: |
          chmod +x install_packages.sh
          ./install_packages.sh
