name: Package Check

on:
  push:
    branches:
      - main

jobs:
  check-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Package Check
        run: |
          chmod +x install_packages.sh
          ./install_packages.sh
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Automatically updated packages"
          git push
        if: success()
